// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hebwfgmkstydkjxzspog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYndmZ21rc3R5ZGtqeHpzcG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjIxNTUsImV4cCI6MjA2NTQzODE1NX0.66LbMXtaxANeomWGH2K8bnhd1iYv8jthUMQFEM_iBV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);